-- Functions:  Date Time Functions


-- CREATE TABLE STUDENT
create table student
	(	id int primary key, 
		firstname varchar(20) not null ,
		lastname varchar(20),
		dob date,
		marks int,
		city varchar(20) );


insert into student values	(101,'Rahul','Shah','01-DEC-1990',85,'Ahmedabad');
insert into student values	(102,'Amit','Verma','03-SEP-1992',90,'Delhi');
insert into student values	(103,'Hitesh','Sharma','04-AUG-1991',56, 'Mumbai');
insert into student values	(104,'Jay','Modi','09-MAY-1995',60, 'Ahmedabad');
COMMIT;

SELECT * 
FROM STUDENT;
        






/* sysdate = current_date*/

/*Sun, Mon,.....*/
-- RESULT WILL BE GIVEN IN SMALL CASE
select to_char(sysdate,'day') as "Day" from dual; 
-- RESULT WILL BE IN UPPERCASE
select to_char(sysdate,'DAY') as "Day" from dual;

/*display current time */
select to_char(sysdate,'hh24:mi:ss am') as "Time" from dual;
select to_char(sysdate,'hh12:mi:ss am') as "Time" from dual;
select to_char(sysdate,'hh24:mi am') as "Time" from dual;
select to_char(sysdate,'hh12:mi am') as "Time" from dual;

/*display current year */
select to_char(sysdate,'year') as "Year" from dual;
select to_char(sysdate,'yyyy') as "Year" from dual;
select to_char(sysdate,'yy') as "Year" from dual;


/*display current month */
select to_char(sysdate,'month') as "Month" from dual;
select to_char(sysdate,'mm') as "Month" from dual;

/*display current date */
select to_char(sysdate,'dd') as "Date" from dual;

/* Date and Time */
select to_char(sysdate,'dd/mm/yyyy hh:mi:ss am day') as "Date" from dual;

/*convert string to date*/
select to_date('27042023','dd/mm/yyyy') from dual;
select to_date('270423','dd/mm/yy') from dual;
select to_date('20230427','yyyy/mm/dd') from dual;
select to_date('202304','yyyy/mm') from dual;

/* difference of the month between two dates*/
select months_between ('20-Aug-2010' , '25-Feb-2011') from dual;
select months_between (current_date,'20-Aug-2010') from dual;
select months_between (current_date,dob) from student;

/* display by adding number of month in date*/
select add_months ('5-Aug-2019',7) from dual;
select add_months (current_date,5) from dual;
select add_months (dob,2) from student;

/*extract year from date*/
select EXTRACT(year FROM current_date)  as "Year" from dual;
select EXTRACT(year FROM dob) as "Year" from student;

/*extract month from date*/
select EXTRACT(month FROM current_date) as "Month"  from dual;
select EXTRACT(month FROM dob) as "Month"  from student;

/*extract day from date*/
select EXTRACT(day FROM current_date) as "Day"  from dual;
select EXTRACT(day FROM dob)  as "Day" from student;

/* manually age calculate*/
select ((months_between (current_date,dob))/12) as "Age "from student;

-- delete from student;	/*delete all records from table*/

-- drop table student;



CREATE TABLE messages(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) NOT NULL
);


INSERT INTO messages(description)
VALUES('Oracle identity column demo with GENERATED ALWAYS');

INSERT INTO messages(id, description)
VALUES(2, 'Oracle identity column example with GENERATED BY DEFAULT');  /* Since we defined the id column as GENERATED ALWAYS, it could not accept any provided value.*/


-- GENERATED BY DEFAULT  AS IDENTITY 

-- DROP TABLE MESSAGES
DROP TABLE messages;

-- create the messages table:

CREATE TABLE messages(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) NOT NULL
);

-- Third, insert a new row into the messages table:

INSERT INTO messages(description)
VALUES('Oracle identity column demo with GENERATED BY DEFAULT');

-- It worked as expected.
-- Fourth, insert a new row into the messages table with a value for the id column:

INSERT INTO messages(id, description)
VALUES(2, 'Oracle identity column example with GENERATED BY DEFAULT');

SELECT * FROM MESSAGES;

-- Finally, attempt to insert a null value into the id column:

INSERT INTO messages(id,description)
VALUES(NULL, 'Oracle identity column demo with GENERATED BY DEFAULT, NULL value');  /*  ERROR */
